# Configuration file
# key = value
quarkus:
  log:
    level: INFO
  http:
    port: 8080
  jaeger:
    enabled: true
    service-name: simple-rest-qarkus
    agent-host-port: localhost:6831
    sampler-type: probabilistic
    sampler-param: 1
    endpoint: http://localhost:14268/api/traces